source "https://rubygems.org"

# Main section
# TODO: why do we need all of this?
gem 'json',                   '1.8.6'
gem 'deep_merge',             '1.0.1'
gem 'rgen',                   '0.6.6'
gem 'ruby-augeas',            '0.4.1'
gem 'ruby-shadow',            '2.2.0'
gem 'rack',                   '1.6.4'
gem 'unicorn',                '4.9.0'

gem 'msgpack',                '1.0.3' # Apache v2

# Puppet tools section
gem 'puppet-syntax',          '2.0.0'
gem 'sensu-plugin',           '1.2.0'     # This is used for check_aws_events
gem 'puppet-lint',            '~> 1.1.0'  # MIT
gem 'serverspec',             '2.36.0'     # MIT
gem 'r10k',                   '1.4.1'

# AWS section
gem 'aws-sdk-resources',      '3.50.0', :require => false
gem 'retries',                '0.0.5', :require => false

# Vault
gem 'hiera-vault',            '0.2.1'

# ipaddress required for puppet-network
gem 'ipaddress',              '0.8.3'

# CFPropertyList gem for macos packages (munki)
gem 'CFPropertyList',         '2.2.7'
